#! /bin/sh
### BEGIN INIT INFO
# Provides:          Gitorious Ultrasphinx
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Ultrasphinx daemon
# Description:       Starts the Ultrasphinx daemons needed by Gitorious
### END INIT INFO

# Author: Fabio Akita <fabioakita@gmail.com>

RETVAL=0
START_CMD="cd /var/www/gitorious/ && rake ultrasphinx:daemon:start Rails.env=production"
STOP_CMD="cd /var/www/gitorious/ && rake ultrasphinx:daemon:stop Rails.env=production"
RESTART_CMD="cd /var/www/gitorious/ && rake ultrasphinx:daemon:restart Rails.env=production"
STATUS_CMD="cd /var/www/gitorious/ && rake ultrasphinx:daemon:status Rails.env=production" 
LOCK_FILE=/var/lock/git-ultrasphinx
PID_FILE=/var/www/gitorious/db/sphinx/log/searchd.pid
 
case "$1" in
  start)
    /bin/su - git -c "$START_CMD"
    ;;
  stop)
    /bin/su - git -c "$STOP_CMD"
    ;;
  status)
    /bin/su - git -c "$STATUS_CMD"
    ;;
        restart)
    /bin/su - git -c "$RESTART_CMD"
                ;;
  *)
    echo $"Usage: $0 {start|stop|restart|status}"
    RETVAL=1
esac
exit $RETVAL
