production: 
  
development:
  # The session secret key (`apg -m 64` is always useful for this kinda stuff)
  cookie_secret: d41d8cd98f00b204e9800998ecf8427e

  # The path where git repositories are stored. The actual (bare) repositories resides
  # in repository_base_path/#{project.slug}/#{repository.name}.git/:
  repository_base_path: "/tmp/git-repos"

  # Stuff that's in the html <head>. custom stats javascript code etc
  extra_html_head_data: 
  
  # System message that will appear on all pages if present
  system_message: 
  
  # Port the ./script/gitorious script should use:
  gitorious_client_port: 3000

  # Host the ./script/gitorious script should use:
  gitorious_client_host: localhost

  # Port grack should use:
  grack_port: 9230

  # Host grack should use:
  grack_host: localhost

  # Host which is serving the gitorious app, eg "gitorious.org"
  gitorious_host: gitorious.test

  # User which is running git daemon
  gitorious_user: git

  # Email address to the support for the Gitorious server
  gitorious_support_email: support@gitorious.org

  # Email spam on server errors to:
  exception_notification_emails:  

  # Mangle visible e-mail addresses (spam protection)
  mangle_email_addresses: true

  # Enable or Disable Public Mode (true) or Private Mode (false)
  public_mode: true

  # Define your locale
  locale: en

  # Where should we store generated tarballs?
  # (should be readable by webserver, since we tell it to send the file using X-Sendfile)
  archive_cache_dir: "/path/to/tarballs-cache"
  # Which directory should we work in when we generate tarballs, before moving 
  # them to the above dir?
  archive_work_dir: "/path/to/tarballs-work"

  # is it only site admins who can create new projects?
  only_site_admins_can_create_projects: false
  
  # Should we hide HTTP clone urls?
  hide_http_clone_urls: false

  # Is this gitorious.org? Read: should we have a very flashy homepage?
  is_gitorious_dot_org: true

  # Pick a default license
  #default_license: GNU Affero General Public License (AGPLv3)

test: 
  # The session secret key (`apg -m 64` is always useful for this kinda stuff)
  cookie_secret: d41d8cd98f00b2ffe9800998ecf8427e

  # The path where git repositories are stored. The actual (bare) repositories resides
  # in repository_base_path/#{project.slug}/#{repository.name}.git/:
  repository_base_path: "/tmp/git-repos"

  # Stuff that's in the html <head>. custom stats javascript code etc
  extra_html_head_data: 
  
  # System message that will appear on all pages if present
  system_message: 
  
  # Port the ./script/gitorious script should use:
  gitorious_client_port: 3000

  # Host the ./script/gitorious script should use:
  gitorious_client_host: localhost

  # Port grack should use:
  grack_port: 9230

  # Host grack should use:
  grack_host: localhost

  # Host which is serving the gitorious app, eg "gitorious.org"
  gitorious_host: gitorious.test

  # User which is running git daemon
  gitorious_user: git

  # Email address to the support for the Gitorious server
  gitorious_support_email: support@gitorious.org

  # Email spam on server errors to:
  exception_notification_emails:  

  # Mangle visible e-mail addresses (spam protection)
  mangle_email_addresses: true

  # Enable or Disable Public Mode (true) or Private Mode (false)
  public_mode: true

  # Define your locale
  locale: en

  # Where should we store generated tarballs?
  # (should be readable by webserver, since we tell it to send the file using X-Sendfile)
  archive_cache_dir: "/path/to/tarballs-cache"
  # Which directory should we work in when we generate tarballs, before moving 
  # them to the above dir?
  archive_work_dir: "/path/to/tarballs-work"

  # is it only site admins who can create new projects?
  only_site_admins_can_create_projects: false
  
  # Should we hide HTTP clone urls?
  hide_http_clone_urls: false

  # Is this gitorious.org? Read: should we have a very flashy homepage?
  is_gitorious_dot_org: true

  # Pick a default license
  #default_license: GNU Affero General Public License (AGPLv3)
