#!/usr/bin/env ruby
# encoding: utf-8

Encoding.default_internal = Encoding::UTF_8
Encoding.default_external = Encoding::UTF_8

require File.expand_path("../../config/environment", __FILE__)

require "activemessaging"

# Make sure stdout and stderr write out without delay for using with daemon like scripts
STDOUT.sync = true; STDOUT.flush
STDERR.sync = true; STDERR.flush

# Start it up!
ActiveMessaging::start