#!/usr/bin/env ruby

incpath = File.dirname(__FILE__)
$: << incpath

require 'messaging'
require 'json'


@publisher = Publisher.new
gitdir = File.expand_path(File.join(incpath, ".."))
# Equivalent to the hash in the model
hashed_dir = gitdir.split('/')[-3,3].join('/').split('.').first
# compat with the old-style paths
hashed_dir = hashed_dir.sub(/^repositories\//, "")


while line = gets
  message = JSON.unparse({:gitdir => hashed_dir, :message => line.chomp, :username => ENV['GITORIOUS_USER']})
  @publisher.post_message(message)
end

puts "[OK]"

